CREATE TABLE CLIENTE (
    ID_Cliente INTEGER PRIMARY KEY AUTOINCREMENT,
    Nome VARCHAR NOT NULL,
    Cognome VARCHAR NOT NULL,
    Email VARCHAR NOT NULL UNIQUE,
    Telefono VARCHAR UNIQUE,
    Citta VARCHAR NOT NULL
);

CREATE TABLE HOTEL (
    ID_Hotel INTEGER PRIMARY KEY AUTOINCREMENT,
    Nome_Hotel VARCHAR NOT NULL,
    Categoria VARCHAR NOT NULL,
    Localita VARCHAR NOT NULL
);

CREATE TABLE DESTINAZIONE (
    ID_Destinazione INTEGER PRIMARY KEY AUTOINCREMENT,
    Citta VARCHAR NOT NULL,
    Nazione VARCHAR NOT NULL,
    Descrizione_Turistica VARCHAR NOT NULL
); 

CREATE TABLE MEZZO (
    ID_Mezzo INTEGER PRIMARY KEY AUTOINCREMENT,
    Tipo_Mezzo VARCHAR NOT NULL
);

CREATE TABLE PACCHETTO (
    ID_Pacchetto INTEGER PRIMARY KEY AUTOINCREMENT,
    Nome_Pacchetto VARCHAR UNIQUE NOT NULL,
    Descrizione VARCHAR NOT NULL,
    Durata_In_Giorni INTEGER NOT NULL,
    ID_Hotel INTEGER NOT NULL,
    ID_Destinazione INTEGER NOT NULL,
    ID_Mezzo INTEGER NOT NULL,
    FOREIGN KEY (ID_Hotel) REFERENCES HOTEL(ID_Hotel),
    FOREIGN KEY (ID_Destinazione) REFERENCES DESTINAZIONE(ID_Destinazione),
    FOREIGN KEY (ID_Mezzo) REFERENCES MEZZO(ID_Mezzo)
);

CREATE TABLE PRENOTAZIONE (
    ID_Prenotazione INTEGER PRIMARY KEY AUTOINCREMENT,
    Data_Prenotazione DATE NOT NULL,
    Numero_Di_Partecipanti INTEGER NOT NULL,
    Importo_Complessivo INTEGER NOT NULL,
    ID_Cliente INTEGER NOT NULL,
    ID_Pacchetto INTEGER NOT NULL,
    FOREIGN KEY (ID_Cliente) REFERENCES CLIENTE(ID_Cliente),
    FOREIGN KEY (ID_Pacchetto) REFERENCES PACCHETTO(ID_Pacchetto)
);
